heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance be sure to 
  update your default key, private_network, flavor, and image name.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu 16.04 LTS
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: demo
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: James
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: Internal


resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: private_network }
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: my_instance }

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }
